name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always
  COMMIT_MSG: 
  SKIP_CI: false
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v1
  
      - name: Check pwd
        run: echo $PWD

      - name: Check mkd and pwd
        run: mkdir a && cd a && echo $PWD
      
      - name: Check pwd
        run: echo $PWD
