name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always
  COMMIT_MSG: 
  SKIP_CI: false
 
jobs:
  check:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v2
  
      - name: Check pwd
        run: pwd

      - name: Install nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      
      - name: Check node version
        run: node -v

      - name: Check ls
        run: ls
      
      - name: Mkd
        run: mkdir abc
      
      - name: Upload result for check
        uses: actions/upload-artifact@v2

  non-checks:
    needs: check
    runs-on: ubuntu-latest
 
    steps:

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2
        
      - name: Check pwd
        run: pwd

      - name: Check ls
        run: ls
      
      - name: check node version
        run: node -v
