name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always
  COMMIT_MSG: 
  SKIP_CI: false
 
jobs:
  check:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v2
  
      - name: Check pwd
        run: echo $PWD

      - name: Install nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Check ls
        run: echo $LS
      
      - name: Mkd
        run: mkdir abc

  non-checks:
    needs: check
    runs-on: ubuntu-latest
 
    steps:
      - name: Check pwd
        run: echo $PWD

      - name: Check ls
        run: echo $LS
      
      - name: check node version
        run: node -v
