name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    if: ${{ !(startsWith(github.event.head_commit.message, 'skip-ci:') ||
      contains(github.event.head_commit.message, 'skip CI')) }}
    runs-on: ubuntu-latest

    steps:
      - name: Hi
        run: echo Hi
  
      - name: Check message
        run: echo ${{ !(startsWith(github.event.head_commit.message, 'skip-ci:') || contains(github.event.head_commit.message, 'skip CI')) }}
