name: CI

on:
  push:
    branches: [master]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    if: ${{ !(startsWith(github.event.head_commit.message, 'skip-ci:') ||
      contains(github.event.head_commit.message, 'skip CI')) }}
    runs-on: ubuntu-latest

    steps:
      - name: Oldest
        run: echo ${{ github.event.commits[0].message }}

      - name: Newest
        run: echo ${{ github.event.head_commit.message }}
  
      - name: Check message
        run: echo ${{ !(startsWith(github.event.head_commit.message, 'skip-ci:') || contains(github.event.head_commit.message, 'skip CI')) }}
