name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy, rustfmt
          target: wasm32-unknown-unknown

      - name: A
        run: cargo +nightly fmt --all
      
      - name: Bash check
        run: which bash
      - name: clippy
        run: cargo +nightly clippy --all
      
      - name: tput output
        run: tput bold && echo "hello, wolrd" && tput sgr0

      - name: tput output
        run: tput bold && echo "hello, wolrd"

      - name: tput output
        run: tput bold && echo "hello, wolrd" && tput normal